services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444" # grid
      - "7900:7900" # watch browser
  npm:
    image: node:22-alpine
    stdin_open: true
    #entrypoint: ["sh", "-c", "cd /test && npm install && node test.js"]
    environment:
      - SELENIUM_REMOTE_URL=http://selenium:4444
      - SELENIUM_BROWSER=chrome
    volumes:
      - ./test:/test
      - ./app:/app:ro
    depends_on:
      - selenium
